name: 'PagerDuty Incidents Action'
description: 'Fetch incidents from PagerDuty based on team and time range'
inputs:
  start_time:
    description: 'Start time of the range (in ISO 8601 format)'
    required: true
  end_time:
    description: 'End time of the range (in ISO 8601 format)'
    required: true
  pagerduty_token:
    description: 'PagerDuty API Token'
    required: true
  team_id:
    description: 'Team Id'
    required: true
  statuses:
    description: 'Incident Statuses'
    required: false
    default: 'triggered'

runs:
  using: 'node20'
  main: 'index.js'
branding:
  icon: "bell"
  color: "purple"
